function [v_v] = fnCubicInterpolate(v_points, mat_x)
%% Based off of code from 
%% 	http://www.paulinternet.nl/?page=bicubic
%%	http://paulbourke.net/miscellaneous/interpolation/

	v_x = reshape(mat_x, size(mat_x,1)*size(mat_x,2),1);
	v_v = zeros(length(v_x),1);

	for i_inc = [1:length(v_x)]
		f_x = v_x(i_inc);

		f_v = v_points(1) + 0.5 * f_x * ...
			(v_points(2) - v_points(0) + f_x * ...
				(2.0 * v_points(0) - 5.0 * v_points(1) + 4.0 * v_points(2) - v_points(3) + f_x * ...
					(3.0 * ...
						(v_points(1) - v_points(2)) ...
						+ v_points(3) - v_points(0) ...
					) ...
				) ...
			); ...

		v_v(i_inc) = f_v;

    end

end
